var cursos = [
    {   nomeCurso: "Desenvolvimento Espiritual", 
        desCargaHoraria: 26, 
        desRequisitos:"Idade mínima de 15 anos, ter completado os cursos de Novidade de Vida, Consolidação Individual e ser batizado.",
        desResumo: "Princípios espirituais colaboram diretamente para santificação e fé. Com uma boa base de conhecimento a respeito da Palavra de Deus, uma pessoa tem condições de crescer e frutificar no Espírito Santo." 
        +"<br/>O Curso de Desenvolvimento Espiritual tem como objetivo principal o entendimento da  vida cristã, que deve seguir nos princípios de caminhar:<br/>"
        +"A.No Espírito, crendo nas promessas de Deus por meio de Jesus Cristo e revestimento do Espírito Santo;<br/>"
        +"B.Em cruz, através do tratamento do caráter, renúncias de pecados e conceitos seculares que impendem a renovação da mente em Cristo;<br/>" 
        +"C.	Em fé, crendo nas obras e sinais do Senhor na vida daqueles que o amam.<br/>", 
        modulos: ["Módulo 1: Caráter de Cristo em nós - três aulas com duração de duas horas cada.", 
        "Módulo 2: Plano de redenção - três aulas com tempo de duas horas cada",
        "Módulo 3: Princípios de revelação da Palavra - duas aulas com tempo de duas horas cada.",
        "Módulo 4: Andando no Espírito - três aulas com tempo de duas horas cada.",
        "Módulo 5: Plenitude no Espírito - duas aulas com tempo de duas horas cada."] }, 
    {   nomeCurso: "Formação de Liderança", 
        desCargaHoraria: 24, 
        desRequisitos:"Requisitos (Idade mínima de 15 anos, ter completado os cursos Novidade de Vida, Consolidação Individual e Desenvolvimento Espiritual. Ser membro de uma célula e ser discípulo.",
        desResumo: "As disciplinas do curso visam capacitar para o cumprimento do “Ide e fazei discípulos”, ordenado por Jesus em Mateus 28,19. Dessa forma, todo conteúdo sinaliza para expansão missionaria da igreja e santificação daqueles que vão executar essa obra: os discípulos e discípulas de Cristo.", 
        modulos: ["Módulo 1: Autoridade espiritual e submissão, quatro aulas com duração de duas horas cada.", 
        "Módulo 2: Liderança eficaz, duas aulas com duração de duas horas cada.",
        "Módulo 3: Consolidação e discipulado.",
        "Módulo 4: Práticas de célula."] }, 
    {   nomeCurso: "Novidade de Vida", 
        desCargaHoraria: 8, 
        desRequisitos:"Livre",
        desResumo: "Destina-se ao acolhimento de pessoas que acabaram de decidir por uma vida nova em Cristo. O objetivo é ensinar princípios da fé cristã e metodista, preparando-as para o batismo.", 
        modulos: [] }, 
    {   nomeCurso: "Sexualidade Sadia", 
        desCargaHoraria: 12, 
        desRequisitos:"Idade mínima 15 anos e ser do sexo masculino.",
        desResumo: "O curso trata a sexualidade masculina de maneira objetiva e responsável a partir das Santas Escrituras,  ensinando conceitos para santificação tanto da mente quanto do corpo.", 
        modulos: [] }, 
    {   nomeCurso: "Libertação e cura da alma.", 
        desCargaHoraria: 40, 
        desRequisitos:"Idade mínima de 18 anos, ser líder de uma célula ou líder em treinamento.",
        desResumo: "O curso colabora para o discernimento de questões espirituais e emocionais, a fim de que maldições sejam quebradas e enfermidades sejam tratadas.", 
        modulos: [] }, 
    {   nomeCurso: "Revelando o Livro do Apocalipse", 
        desCargaHoraria: 48, 
        desRequisitos:"Livre",
        desResumo: "Estudo das promessas de Deus contidas no livro do Apocalipse e introdução da visão do papel da igreja na reconstrução do relacionamento entre Deus e a humanidade por meio de Jesus Cristo.", 
        modulos: [] }, 
    {   nomeCurso: "Família de Deus", 
        desCargaHoraria: 20, 
        desRequisitos:"Participação do casal.",
        desResumo: "O curso objetiva tratar assuntos dos lares conforme as Santas Escrituras", 
        modulos: ["Módulo 1: Descobrindo a paternidade de Deus para restauração do caráter - Duas aulas com tempo de duas horas cada.", 
        "Módulo 2: Casamento curado - Quatro aulas com tempo de duas horas cada.",
        "Módulo 3: Educando filhos e filhas a maneira de Deus - Quatro aulas com tempo de duas horas cada."] }
    ];